[package]
name = "astra-record"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
astra-book.workspace = true
astra-types.workspace = true
clap.workspace = true
ctrlc = "3"
postcard.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tungstenite.workspace = true
uuid.workspace = true
zstd.workspace = true
